### ISSUE TITLE
Use a custom config file

### ISSUE THREAD

**Issue by Wandmalfarbe** [aesy/yamllint-intellij#1]
I know that a config file will be applied when one resides in the current project. I want to use a global configuration file that resides outside the project. Is this possible? If not, can this be implemented?

**Comment by aesy** [comment]
Hi, as you probably know a first version of the plugin hasn't been published yet, there are a few features I want to add first. Being able to specify a configuration file to use is one of them! The plan is to be able to specify the file on a project to project basis and just default to the project `.yamllint` if one exists.

This is already mostly implemented, I just need to find the time to finish it up and publish it.

**Comment by aesy** [comment]
A release candidate has been pushed to the plugin repository's [beta channel](https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#configuring-a-custom-channel-in-intellij-platform-based-ides) and can be found [here](https://plugins.jetbrains.com/plugin/15349-yamllint). Open new issue tickets if anything seems out of order! I'll push it to the stable if everything seems fine in a couple of weeks.
