### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by romanad** [aesy/yamllint-intellij#11]
Does it work on Windows?
I installed plugin but nothing happens concerning error detection.

**Comment by aesy** [comment]
It should, yeah! Did you enable it in the settings and configure the path to the Yamllint executable?

**Comment by aesy** [comment]
Feel free to reopen if you have any more information

**Comment by Tarek90** [comment]
But need to install extra yamllint.exe or somthing to chose in the executable path or what? is it enough to install to only the plugin inside the intelij? I didn't got it

**Comment by aesy** [comment]
The plugin doesn't bundle Yamllint, so you'll need to [install it](https://yamllint.readthedocs.io/en/stable/quickstart.html#installing-yamllint) on your machine and select the executable in the settings, if it isn't auto-detected.
