### ISSUE TITLE
colon in echo string raises warning

### ISSUE THREAD

**Issue by Zyantist** [aesy/yamllint-intellij#12]
Hello, 

thanks for this very helpful plugin. 

Today, I encountered an issue when linting my gitlab CI yaml: 

Does not raise a warning:
```yaml
script:
    - echo "VERSIONCOMPONENTTOINCREMENT= ${VERSIONCOMPONENTTOINCREMENT}"
```

Raises a warning:
```yaml
script:
    - echo "VERSIONCOMPONENTTOINCREMENT: ${VERSIONCOMPONENTTOINCREMENT}"
```

![image](https://github.com/user-attachments/assets/25c54b25-af4f-4667-bef0-5db5766f6f00)

I think it, this might be an issue with the plugin that yamllint depends on, but the colorization is also odd:
![image](https://github.com/user-attachments/assets/a57ee840-7336-4ac3-88ba-96895dbf3f59)

-------------------------------------
Fedora 39 

PyCharm 2024.2 (Professional Edition)
Build #PY-242.20224.347, built on August 9, 2024
XXXX
XXXX
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.9.12-200.fc40.x86_64
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3974M
Cores: 20
Registry:
  debugger.watches.in.variables=false
  ide.experimental.ui=true
  ide.images.show.chessboard=true
  terminal.new.ui=true
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.240807.213)
  artsiomch.meson.syntax (203.1.0)
  some.awesome (1.15)
  io.aesy.yamllint (0.4)
Current Desktop: GNOME

**Comment by aesy** [comment]
Hi @Zyantist, this isn't actually a warning from this plugin, but from IntelliJ's built-in YAML inspection called "Validation by JSON Schema". It says that the type isn't matching the schema that's chosen (which you can see in the status bar at the bottom). I don't know whether that's correct or why the highlighting changes when you change the line, but if you think this is wrong then you're best off submitting a ticket in Jetbrains' [issue tracker](https://youtrack.jetbrains.com/issues/IDEA). Good luck!
