### ISSUE TITLE
Yamllint is not working on windows

### ISSUE THREAD

**Issue by Tarek90** [aesy/yamllint-intellij#13]
I installed the plugin in IntelliJ, but whenever I select a directory in the executable path, I receive the following error:

"Failed to execute yamllint. Failed to execute command. Cannot run program 'C:\Users\xxx.xxx\Desktop' (in directory 'C:\at\test\et'): CreateProcess error=5, Access Denied."

There are no instructions on what should be selected in the executable path. Do I need to install a yamllint.exe or another specific file?

Thank you for your support.

**Comment by aesy** [comment]
You need to install Yamllint and then select the Yamllint executable in the settings. Install it following the instructions at [yamllint.readthedocs.io](https://yamllint.readthedocs.io/en/stable/quickstart.html#installing-yamllint). On windows, if you install with pip, the path is usually `%APPDATA%\Roaming\Python\...\Scripts\yamllint.exe`.

**Comment by Tarek90** [comment]
Thanks for you answer, now it works
