### ISSUE TITLE
Please add/fix support for `ignore-from-file` option

### ISSUE THREAD

**Issue by The-Judge** [aesy/yamllint-intellij#6]
When `ignore-from-file` is used with some top-level filenames, the plugin always shows an error about that file was not found. For example:

In `${PROJECT_ROOT}/.yamllint`:
```
ignore-from-file: [.gitignore, .yamlignore]
```

Results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.28.0', 'console_scripts', 'yamllint')())
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/cli.py", line 201, in run
    conf = YamlLintConfig(file=user_global_config)
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/config.py", line 44, in __init__
    self.parse(content)
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/config.py", line 113, in parse
    self.ignore = pathspec.PathSpec.from_lines('gitwildmatch', f)
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/pathspec/pathspec.py", line 122, in from_lines
    patterns = [pattern_factory(line) for line in lines if line]
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/pathspec/pathspec.py", line 122, in <listcomp>
    patterns = [pattern_factory(line) for line in lines if line]
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/fileinput.py", line 256, in __next__
    line = self._readline()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/fileinput.py", line 390, in _readline
    self._file = open(self._filename, self._mode, encoding=encoding, errors=self._errors)
FileNotFoundError: [Errno 2] No such file or directory: '.gitignore'
```

This is from latest PyCharm.

The same can be achieved on the shell, if setting the `YAMLLINT_CONFIG_FILE` pointing to the `.yamllint` - file and executing `yamllint .` in a sub-dir where no `.gitignore` file (or any file matching a pattern listed in `ignore-from-file` is found:

```
tasks $ export YAMLLINT_CONFIG_FILE=/Users/mrichter/ansible/.yamllint
tasks $ pwd
/Users/mrichter/ansible/roles/openldap/tasks
tasks $ yamllint .
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: '.gitignore'
```

Since this behavior seems to be within `yamllint`, a potential workaround might be to copy the defined file configured in `Path to yamllint config` to some temporary location and prefix the `ignore-from-file`-patterns with absolute paths from the content root:

`ignore-from-file: [.gitignore, .yamlignore]` ->
`ignore-from-file: [/Users/mrichter/ansible/.gitignore, /Users/mrichter/ansible/.yamlignore]`

**Comment by aesy** [comment]
Hey, thanks for reporting this! I haven't used that setting before, so I've never run into this problem.

The problem here has to do with which work directory is used when running `yamllint`. The project root is normally used as the work directory, except when linting things that are in memory (for example when there are unsaved changes to a file) in which case a temporary file is created and used instead. There's really no reason why the project root can't be used as work directory in that case too, as long as there is a project (there's none when a single file is opened for example). I'll push a fix for this!

**Comment by aesy** [comment]
Fixed in 39dddf8a6ce2e919e677b1e6e7e33d77315fc379. I've published a new release (`0.2`) that should be available in a few days. Please let me know if it works for you or if you encounter any other problems!

**Comment by The-Judge** [comment]
WOW - great reaction time! 👍
As soon as 0.2 is available, I will happily test it.

**Comment by The-Judge** [comment]
You implemented this 3 days ago and still, it does not show on [JB-Marketplace page](https://plugins.jetbrains.com/plugin/15349-yamllint).
Is there a binary you can provide for testing, which does not need to travel via JB-Marketplace publication?

**Comment by aesy** [comment]
Thanks a lot for testing it out! I had to fix some compatibility issues during review so it's taking a bit longer, be patient :smile:
