### ISSUE TITLE
Auto-detect yamllint managed by poetry or other project SDK

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [aesy/yamllint-intellij#7]
It would be nice if the yamllint plugin could auto-detect the yamllint instance installed within the virtual environment for my project, rather than defaulting to a "yamllint" that is expected to be in my PATH.

For example, the [Mypy plugin](https://github.com/leinardi/mypy-pycharm/) seems to do this nicely:

<img width="975" alt="Screenshot 2023-03-22 at 5 28 00 PM" src="https://user-images.githubusercontent.com/22308682/227068343-10e7bdc3-7aee-462e-9281-4a666d1a76be.png">

I did not have to change any settings for this to work.

Glancing at the Mypy plugin source code, it looks like this is generally the place where auto-detection takes place: https://github.com/leinardi/mypy-pycharm/blob/26299d03651b45f8721ea36b8d538be7a020b501/src/main/java/com/leinardi/pycharm/mypy/mpapi/MypyRunner.java

The source code for the config panel I screenshotted above appears to be: https://github.com/leinardi/mypy-pycharm/blob/26299d03651b45f8721ea36b8d538be7a020b501/src/main/java/com/leinardi/pycharm/mypy/ui/MypyConfigPanel.java#L98

**Comment by aesy** [comment]
Good idea and thank you for providing an example! I will be looking into this.

**Comment by aesy** [comment]
The plugin should now be able to find the Yamllint executable if you've installed it through Pipenv, Poetry or any other supported Python SDK as long as you've configured and selected it for your project. It will be included in the next, `0.3`, release. 

Thanks for the suggestion :+1:
