### ISSUE TITLE
request: add option to make config file global

### ISSUE THREAD

**Issue by ReenigneArcher** [aesy/yamllint-intellij#8]
This issue is to request a feature to make a config file apply globally across multiple projects, as it is kind of annoying to have to specify the config file for every project.

It would probably be nice to have a project specific override.

**Comment by aesy** [comment]
This should already be supported natively by the IDE, sorta. If you go to "File > New Projects Setup > Settings for New Projects..." and change the Yamllint settings, then it should then be applied to new projects.

**Comment by ReenigneArcher** [comment]
Thanks, I didn't know about that menu.
