### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by jon-strayer** [aesy/yamllint-intellij#9]
After a couple days of using the plugin I started to get this error:
Failed to execute yamllint An unexpected error occurred: Traceback (most recent call last): File "/opt/homebrew/bin/yamllint", line 8, in   sys.exit(run()) ^^^^^ File "/opt/homebrew/Cellar/yamllint/1.32.0/libexec/lib/python3.11/site-packages/yamllint/cli.py", line 249, in run prob_level = show_problems(problems, 'stdin', args_format=args.format, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I thought you would want to know.

**Comment by aesy** [comment]
Hey, thanks for the report. I can't tell what this error is since it's an internal Yamllint error which is missing most of the stacktrace. I'll close this for now but if anyone else encounters it then I'd appreciate some more information.
